#!/bin/bash

CURDIR=$(dirname "$0")

REMOTE_MACHINE=6.6.6.15
REMOTE_PATH=/e/adebug
TOS_ROOT=E:/ADEBUG
PRG=$TOS_ROOT/RELEASE/MIDIPLAY.TTP
PARAM=$TOS_ROOT/U8_ETHPL.MID

echo Launching Atari native debugger with $PRG and parameters: $PARAM

#URL=http://$REMOTE_MACHINE$REMOTE_PATH/ADEBUG.TTP?run="$PRG $PARAM"
#curl -0 $URL

${CURDIR}/uip/uip-run.py $REMOTE_MACHINE$REMOTE_PATH/ADEBUG.TTP $PRG $PARAM