
name: amidilib-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-atari-target:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - run: |
          echo Update and get build prerequisities
          apt-get install -y software-properties-common
          apt-get update -qq
          apt-get install -y scons upx
          echo TODO get/install vasm
      - run: | 
          echo Installing libcmini ...
          mkdir ../libcmini
          cd ../libcmini
          wget -q -O - "https://github.com/freemint/libcmini/releases/download/v0.54/libcmini-0.54.tar.gz" | tar xzf -
          echo TODO build libcmini
      - run: | 
          echo Getting latest gcc minimal startup
          ./getLatestStartup.sh
      - run: | 
          echo Installing gcc in /opt/cross-mint
          mkdir /opt/cross-mint
          wget -q -O - "https://nokturnal.pl/downloads/atari/toolchains/m68k-atari-mint-base-20200501-linux64.tar.xz"
          tar -C /opt/cross-mint --strip-components=1 -xf ./m68k-atari-mint-base-20200501-linux64.tar.xz 
      - run: echo "Done"
